x-airflow-common:  
  &airflow-common
  env_file: .env
  image: apache/airflow:2.9.0
  environment:
    &airflow-env
    AIRFLOW__CORE__EXECUTOR: ${AIRFLOW__CORE__EXECUTOR:-LocalExecutor}
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: ${AIRFLOW__DATABASE__SQL_ALCHEMY_CONN:-postgresql+psycopg2://airflow:airflow@postgres/airflow}
    AIRFLOW__CORE__FERNET_KEY: ${AIRFLOW__CORE__FERNET_KEY}
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: ${AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION:-'True'}
    AIRFLOW__CORE__LOAD_EXAMPLES: ${AIRFLOW__CORE__LOAD_EXAMPLES:-'False'}
    AIRFLOW__CORE__LOGGING_LEVEL: ${AIRFLOW__CORE__LOGGING_LEVEL:-INFO}
    AIRFLOW__WEBSERVER__EXPOSE_CONFIG: ${AIRFLOW__WEBSERVER__EXPOSE_CONFIG:-'True'}
    AIRFLOW__WEBSERVER__SECRET_KEY: ${AIRFLOW_WEBSERVER_SECRET_KEY}
    POSTGRES_URI: postgresql://airflow:airflow@postgres:5432/airflow
  volumes:
    # Mount ETL project
    - ./airflow/dags:/opt/airflow/dags/etl
    - ./airflow/etl:/opt/airflow/etl
    - ./plugins:/opt/airflow/plugins/etl
    - ./include:/opt/airflow/include/etl

    #  data folder (optional)
    - ./data:/opt/airflow/data

    # requirements (optional)
    - ./requirements.txt:/requirements-etl.txt

services:
  airflow-init:
    <<: *airflow-common
    container_name: airflow-init
    command: >
      bash -c "pip install -r /requirements-etl.txt &&
               airflow db init &&
               airflow users create --username ${AIRFLOW_ADMIN_USER:-admin} --password ${AIRFLOW_ADMIN_PASSWORD:-admin} --firstname Admin --lastname User --role Admin --email admin@example.com"
    networks:
      - health-net

  airflow-webserver:
    <<: *airflow-common
    container_name: airflow-webserver
    ports:
      - "8080:8080"
    command: >
      bash -c "pip install -r /requirements-etl.txt &&
               airflow webserver"
    networks:
      - health-net

  airflow-scheduler:
    <<: *airflow-common
    container_name: airflow-scheduler
    command: >
      bash -c "pip install -r /requirements-etl.txt &&
               airflow scheduler"
    networks:
      - health-net

networks:
  health-net:
    external: true
    name: health-net